version: "3.3"
services:

  app:
    build: .
    networks:
      - networking


   # Misc Storage
  postgres:
    container_name: "DB_postgres"
    restart: "always"
    image: postgres
    env_file:
      - ./metabase/config/postgres_exemple.env
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data/
    ports:
      - 54320:5432



# Volumes to persist data
volumes:
  postgres_volume:
  
networks:
  networking: